steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/rapid-jaguar-prisma/multi-client', './client' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/rapid-jaguar-prisma/multi-nginx', './nginx' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/rapid-jaguar-prisma/multi-server', './server' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/rapid-jaguar-prisma/multi-worker', './worker' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rapid-jaguar-prisma/multi-client']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rapid-jaguar-prisma/multi-nginx']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rapid-jaguar-prisma/multi-server']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/rapid-jaguar-prisma/multi-worker']
images: [
  'gcr.io/rapid-jaguar-prisma/multi-client',
  'gcr.io/rapid-jaguar-prisma/multi-nginx',
  'gcr.io/rapid-jaguar-prisma/multi-server',
  'gcr.io/rapid-jaguar-prisma/multi-worker'
]